#!/bin/bash

echo Hosts script
echo hostname is $HOSTNAME
echo IP is $(hostname -I)
echo Network inteface card info
sudo lshw -class network
echo ---------
read -p "enter IP > " ipad
ping $ipad -c 5
read -p "set name > " name
printf "${ipad}		${name}" >> /etc/hosts

echo active IPs
nmap -sn 192.168.1.* --open | grep -v '^Host is' | cut -d" " -f 5,6

echo -----
read -p "enter port to kill process of > " porttokill
processid=$(sudo lsof -ti :${porttokill})
if [ -z ${processid} ]
then
	echo "Process doesn't exist."
else
	kill -9 ${processid}
	echo "death reaches us all eventually. Process ID ${processid} on port ${porttokill} killed."
fi

