#!/bin/bash
read -p "enter password > " pass1
pass=$(echo "${pass1}" | md5sum)
starttime=$(date)
function check () {
	echo "check $1 agaisnt $pass1"
	check=$(echo $1 | md5sum)
        if [[ ${check} = ${pass} ]]
        then
        	echo "Cracked! the pass was ${pass1}"
                echo "start at ${starttime}"
		echo "finish at $(date)"
		printf 'Time was: %f\n' "${SECONDS}"
                exit
        fi
}

hackletters=()
for i in {a..z}
do
	hackletters=(${hackletters[@]}  "${i^^}" "${i}")
done
for i in {0..9}
do
	hackletters=(${hackletters[@]} $i)
done	
echo ${hackletters[@]}
for letter1 in ${hackletters[@]}
do
	check ${letter1}
	for letter2 in ${hackletters[@]}
	do
		var=${letter1}${letter2}
		check $var
		for letter3 in ${hackletters[@]}
		do
			var=${letter1}${letter2}${letter3}
			check $var
			for letter4 in ${hackletters[@]}
			do
				var=${letter1}${letter2}${letter3}${letter4}
				check $var
			done	
		done
	done
done
